支持像eglot 一样在elisp 端配置client-capabilities，并全局支持snippet ，并gopls server端配置支持snippet 等
manateelazycat/lsp-bridge pull request #118
Opened 2022-05-19 16:06 UTC by jixiuf

client-capabilities 应该是client 端的能力， 而不应该在 langserver的配置文件中进行配置。

2022-05-19 16:28 UTC, jixiuf commented
打个这个补丁之后，会有snippet 返回，但返回的snippet 似乎不太正确，具体问题在哪 没研究清楚。
比如 返回如下数据
```
         {
            "label": "fmt.Sprintf",
            "labelDetails": {},
            "kind": 3,
            "detail": "func(format string, a ...any) string",
            "documentation": "Sprintf formats according to a format specifier and returns the resulting string.\n",
            "sortText": "00001",
            "filterText": "fmt.Sprintf",
            "insertTextFormat": 2,
            "textEdit": {
               "range": {
                  "start": {
                     "line": 8,
                     "character": 12
                  },
                  "end": {
                     "line": 8,
                     "character": 12
                  }
               },
               "newText": "fmt.Sprintf(${1:})"
            }
         },

```
需要关注的有两点
`func(format string, a ...any) string` 实际有两个参数,`newText`中的snippet `"fmt.Sprintf(${1:})` 只有一个占位符。
不知道其他语言有没有这个问题，需要大家研究下。

2022-05-19 16:41 UTC, zerolfx commented
`fmt.Sprintf` 接受的参数个数是 >= 1，所以一个占位符也挺合理的。

2022-05-19 17:14 UTC, jixiuf commented
问题已经定位，是lsp-bridge 对server 发起的  workspace/configuration请求，返回空数据
handle_workspace_configuration_request处:
https://github.com/jixiuf/lsp-bridge/blob/master/core/lspserver.py#L319

把将
```
    def handle_workspace_configuration_request(self, name, request_id, params):
        self.sender.send_response(request_id, [])

``` 
改成 

```
    def handle_workspace_configuration_request(self, name, request_id, params):
        self.sender.send_response(request_id, [  {"usePlaceholders": True}
```
用gopls 就能补全args了。
目前还不清楚 应该怎么实现这块。

2022-05-19 22:57 UTC, manateelazycat commented
感谢补丁，建议elisp只提供选项，python端来动态调整json比较合适，代码也更干净。

2022-05-20 06:19 UTC, zerolfx commented on core/lspserver.py
> +            self.client_info["capabilities"]["textDocument"]["completion"]["completionItem"]["snippetSupport"]=False
`self.client_info[...] = is_snippet_support`

2022-05-20 06:19 UTC, zerolfx commented on lsp_bridge.py
> +                client_info=load_lsp_client_info()
这个 client_info 是不是每个 lsp server 都是一样的？如果是的话没必要每次创建 lsp server 时 load 一下

2022-05-20 06:19 UTC, zerolfx commented on lsp-bridge-client.json
> +}
这个文件是希望用户自己改吗？如果不是的话，直接作为 python 的常量会比较好。

2022-05-20 06:19 UTC, zerolfx commented on core/lspserver.py
> +        is_snippet_support = get_emacs_func_result("is-snippet-support") # "true" or "false"
`get_emacs_var` 在这里不好用么？如果好用的话 elisp 里还能省个函数

2022-05-20 06:55 UTC, jixiuf commented on core/lspserver.py
> +        is_snippet_support = get_emacs_func_result("is-snippet-support") # "true" or "false"
定议成变量的话，可能会有问题，比如yasnippet lazy load  前后， `lsp-bridge--snippet-expansion-fn` 返回的结果可能不太一样。

2022-05-20 06:56 UTC, jixiuf commented on lsp-bridge-client.json
> +}
理论上是不需要用户改的。

2022-05-20 06:57 UTC, jixiuf commented on core/lspserver.py
> +            self.client_info["capabilities"]["textDocument"]["completion"]["completionItem"]["snippetSupport"]=False
> is_snippet_support

这样好像不行. nil 转到python 这边似乎变成了 [].

2022-05-20 06:58 UTC, jixiuf commented on lsp_bridge.py
> +                client_info=load_lsp_client_info()
看eglot 的代码，它的client_info 部分属性是根据server 不同发生变化的，比如 是否支持tramp 
https://github.com/joaotavora/eglot/blob/master/eglot.el#L674,所以这里也保留相同的机制。

2022-05-20 08:13 UTC, manateelazycat requested changes

2022-05-20 08:13 UTC, manateelazycat commented on lsp-bridge.el
> +
这个为啥要写成 if xxx t else nil 的形式？ 直接 ```（lsp-bridge--snippet-expansion-fn）```不行吗？

2022-05-20 08:15 UTC, manateelazycat requested changes

2022-05-20 08:15 UTC, manateelazycat commented on lsp_bridge.py
> +"""
全局变量用大写

2022-05-20 08:23 UTC, jixiuf commented on lsp_bridge.py
> +"""
> 全局变量用大写

done

2022-05-20 08:29 UTC, jixiuf commented on langserver/gopls.json
> +    }
https://github.com/golang/tools/blob/master/gopls/doc/settings.md
这里有每个选项的含义
usePlaceholders： 应该就是snippet方面的支持 
completeUnimported: 如果有未导入的package ,补全时自动导入它
staticcheck: 跟flymake 一些静态检查相关的， 关闭它。
allowImplicitNetworkAccess: 是否自动从网上拉取第3方依赖
experimentalWorkspaceModule: 允许一个git 项目下的目录有多个go.mod 文件时，支持 multi-module workspaces.（这个应该是开启gopls 相应的能力，具体lsp-bridge 若还不支持，估计是不生效的，这个理论上可以在client端的 capabilities 里配置（没细研究)
allowModfileModifications: 是不允许gopls 更改项目的go.mod

2022-05-20 09:26 UTC, jixiuf commented on lsp-bridge.el
> +
fixed .

2022-05-20 09:39 UTC, zy9306 commented on langserver/gopls.json
> +    }
只是个建议，这个交给用户自定义比较好吧，只要和用户说明配置意义让用户自行决定，默认配置应该和上游服务器的默认配置保持一致，即默认为空，因为上游可能会更改或废弃某些配置

2022-05-20 10:02 UTC, jixiuf commented on langserver/gopls.json
> +    }
那就仅保留 两个选项

    "gopls": {
      "usePlaceholders": true,
      "completeUnimported": true
    }

1. 是否开启snippet ,我们这里把gopls(server)端的开关打开，只需要通过是否安装了yasnippet 来控制即可(代码里`lsp-bridge--snippet-expansion-fn` 实现此功能。
2. 是否自动引入package ,也是把gopls(server)的开关打开，用户只需要 使用`lsp-bridge-enable-auto-import` 来控制。
避免为了开启一个功能，client/server 两端都要去调整。 很容易迷惑人。

2022-05-20 13:37 UTC, zerolfx commented on core/lspserver.py
> +        if is_snippet_support==[]: # nil -> []
一般我们不写 `x == []` 可以 `not x` 或者 `len(x) == 0`，这里我们也可以写成 `self.xxx[...] = bool(x)`

另外需要你格式化一下 Python 代码，目前仓库里的 Python 运算符周围都是有空格的

2022-05-20 13:37 UTC, zerolfx commented on lsp_bridge.py
> +    return json.loads(LSP_CLIENT_INFO)
直接用 Python 的 dict 作为常量不好吗？

2022-05-20 14:32 UTC, jixiuf commented on lsp_bridge.py
> +    return json.loads(LSP_CLIENT_INFO)
fixed.  
 python对我来说，现学现卖,二把刀。

2022-05-20 14:33 UTC, jixiuf commented on core/lspserver.py
> +        if is_snippet_support==[]: # nil -> []
fixed.

2022-05-20 14:42 UTC, jixiuf commented on lsp_bridge.py
> +    return json.loads(LSP_CLIENT_INFO)
我有个疑问，python 的dict 在进行赋值的时候是深拷贝 还是浅拷贝 。 现在是把这个常量 赋值到`LspServer.client_info`.
后面对  `LspServer.client_info` 的修改  会影响其他`LspServer.client_info`吗.
还有 就是`LspServer.client_info` 有没有存在的必要 ，我也拿不准。 大家讨论下。

2022-05-20 15:41 UTC, manateelazycat requested changes

2022-05-20 15:41 UTC, manateelazycat commented on lsp_bridge.py
> +                client_info=LSP_CLIENT_INFO,
client_info 去掉

2022-05-20 15:54 UTC, manateelazycat approved these changes

2022-05-20 15:56 UTC, jixiuf commented on lsp_bridge.py
> +LSP_CLIENT_INFO = {
done

2022-05-20 15:56 UTC, jixiuf commented on core/lspserver.py
> +        self.client_info = client_info
done

2022-05-20 15:57 UTC, jixiuf commented on core/lspserver.py
> +    def __init__(self, message_queue, project_path, server_info, server_name, client_info):
done

2022-05-20 15:57 UTC, jixiuf commented on lsp_bridge.py
> +                client_info=LSP_CLIENT_INFO,
done

2022-05-20 15:57 UTC, jixiuf commented
刚才少 了 `import copy`

2022-05-20 15:59 UTC, merged

2022-05-20 16:00 UTC, manateelazycat commented
合并了，大佬辛苦啦！