Add citre backend support
manateelazycat/lsp-bridge pull request #333
Opened 2022-08-31 16:34 UTC by wcq062821

<img width="862" alt="image" src="https://user-images.githubusercontent.com/19771608/187729920-c0f75221-8693-4353-9c09-45d302fd095c.png">
考虑到目前还是有一些语言如硬件描述语言(VHDL, Verilog, Systemverilog) 还没有成熟的LSP后端， 绝大部分硬件描述语言的插件还是利用Tags来补全和跳转， 所以对lsp-bridge添加了Citre的支持，用起来效果还不错：）

2022-08-31 23:02 UTC, manateelazycat requested changes

2022-08-31 23:02 UTC, manateelazycat commented on acm/acm-backend-citre.el
> +            (setq icon (conver-icon-for-hdl-language annotation))
这两个 setq 改成 let* 的形式

2022-08-31 23:02 UTC, manateelazycat commented on acm/acm-backend-citre.el
> +           icon)
这两个变量声明去掉， 放到 dolist 里面去。

2022-08-31 23:06 UTC, manateelazycat commented
图标那里建议不要转换， 差的图标参考这个补丁 https://github.com/manateelazycat/lsp-bridge/commit/d6be2c9ecfaedef8866df161bb6de13a489fa303

图标从 https://materialdesignicons.com 里面找合适的， 把图标名字添加到 acm-icon-alist 里面后， 执行命令 acm-icon-fetch-all 后会自动下载SVG图标。

2022-09-01 00:35 UTC, wcq062821 commented
感谢大佬建议， 已经改好了。

2022-09-01 03:12 UTC, merged

2022-09-01 03:12 UTC, manateelazycat commented
> 感谢大佬建议， 已经改好了。

大佬辛苦啦， 补丁质量非常高。