#336
manateelazycat/lsp-bridge pull request #337
Opened 2022-09-02 08:48 UTC by Joxos

2022-09-02 08:49 UTC, Joxos commented
just add volar_windows.json

2022-09-02 10:39 UTC, manateelazycat commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
this is real path for windows？

2022-09-02 16:00 UTC, Joxos commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
this isn't the real path on my computer, and user should modify it manually.

2022-09-02 22:12 UTC, manateelazycat commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
please change to real path

2022-09-02 22:54 UTC, MatthewZMD commented
Please change the title to something that makes sense.

2022-09-03 01:35 UTC, Joxos commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
this path will be different if user chose different package manager to install (e.g. pnpm or yarn)

2022-09-03 01:54 UTC, manateelazycat commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
> 

use npm path, and notify user use npm install tsserverlibrary in README, not let user edit json file.

2022-09-03 02:15 UTC, Joxos commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
i'm very glad to do that and finish this pr, but:
1. `tsserverlibrary` isn't a package. 
![image](https://user-images.githubusercontent.com/37507136/188251972-f369744b-e05f-402a-8e51-95e8a62497fe.png)
![image](https://user-images.githubusercontent.com/37507136/188251975-e0db9851-a182-40a5-969a-f046742d9ff5.png)

2. the real path on my computer is `C:\Users\Joxos\AppData\Local\pnpm\global\5\.pnpm\typescript@4.7.4\node_modules\typescript\lib` and you can see this is even related to the version code, either. so if typescript has an update, this path would be invalid.
3. the path is also related to the choice of different package manager.

and here i have some suggestions for this problem:

1. ask user to modify it manually.
2. join the path and the version code by getting it through `npm list -g`

2022-09-05 13:42 UTC, manateelazycat commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
这个补丁还要想办法，用户改路径，门槛太高了

2022-09-06 05:58 UTC, Joxos commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
可否让其储存一个列表，包含同一版本下`npm`、`yarn`和`pnpm`对应的路径，然后挨个检查有效性？

甚至这样的话，还可以挨个尝试版本号，试出来有效就存储到`lsp-bridge`的工作目录下，每次启动就用这个，这样只用检查一遍就行了，后面都能用。

等到这个路径失效后，再调用尝试的函数，试出一个新的有效路径（失效可能是用户更新版本号之类的）。

如果实在没找到，那就是用户没有安装`tsserverlibrary`，提示用户安装。

您看如何？

2022-09-06 06:06 UTC, manateelazycat commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
VSCode 在 Windows 上怎么做到开箱即用的呢？

2022-09-06 12:17 UTC, Joxos commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
他们的`tsserverlibrary`都是通过`import`导入的，编译器会自动处理好路径。

```typescript
import * as ts from "typescript/lib/tsserverlibrary"
```

见：[volar仓库中所有的tsserverlibrary导入](https://github.com/johnsoncodehk/volar/search?p=1&q=tsserverlibrary)

2022-09-06 23:40 UTC, manateelazycat commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
> 他们的`tsserverlibrary`都是通过`import`导入的，编译器会自动处理好路径。
> 
> ```ts
> import * as ts from "typescript/lib/tsserverlibrary"
> ```
> 
> 见：[volar仓库中所有的tsserverlibrary导入](https://github.com/johnsoncodehk/volar/search?p=1&q=tsserverlibrary)

没看懂，我们能利用这种方法解决各操作系统路径不一致的问题吗？

2022-09-07 00:32 UTC, Joxos commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
我的错，没有做好调查。npm安装的话路径是固定的：`C:/Users/<user_name>/AppData/Roaming/npm/node_modules/typescript/lib/tsserverlibrary.js`

所以可以通过`~/`或者`%USERPROFILE%`进行拼接。

2022-09-07 00:32 UTC, Joxos commented on langserver/volar_windows.json
> +      "serverPath": "C:/path/to/tsserverlibrary.js"
可是我尝试的两种都不行，正在调试中。

2022-09-07 01:47 UTC, Joxos commented
现在我的机子上测试是可以了，但是补丁多少质量太低（因为没看完整个lsp-bridge的设计），不过已经可用了。

2022-09-07 01:47 UTC, Joxos commented
@manateelazycat

2022-09-07 04:58 UTC, Joxos commented
审查无误请合并 @manateelazycat

2022-09-07 14:17 UTC, manateelazycat requested changes

2022-09-07 14:18 UTC, manateelazycat requested changes

2022-09-07 14:18 UTC, manateelazycat commented on core/lspserver.py
> +            if "%USERPROFILE%" in initialize_options['typescript']['serverPath']:
要检查serverPath这个key是否存在， 否则这行代码会挂。

2022-09-07 14:21 UTC, manateelazycat requested changes

2022-09-07 14:21 UTC, manateelazycat commented on core/utils.py
> +import subprocess
用 os.environ 以后， subprocess 不再需要。

2022-09-07 14:29 UTC, manateelazycat commented
你改完代码后， 需要 rebase 一下。

2022-09-08 09:46 UTC, Joxos commented
已修改完毕，审查无误请合并，有问题请指正，多谢了！ @manateelazycat

2022-09-08 10:25 UTC, Joxos commented
使用git不熟练，抱歉了。现在可以合并。 @manateelazycat

2022-09-08 10:33 UTC, manateelazycat commented
> 使用git不熟练，抱歉了。现在可以合并。 @manateelazycat

没有rebase成功啊，还有冲突。

2022-09-08 12:18 UTC, merged