Fixes for omnisharp paths on Windows and support for omnisharp-dotnet
manateelazycat/lsp-bridge pull request #436
Opened 2022-11-30 10:57 UTC by JordanAnthonyKing

2022-11-30 11:42 UTC, manateelazycat commented on langserver/omnisharp-dotnet_windows.json
> +    "command": ["C:\\Users\\Jordan\\.emacs.d\\.cache\\omnisharp\\OmniSharp.exe",
C:\\Users\\Jordan replace with `%USERPROFILE%` , will work?

2022-12-01 00:29 UTC, manateelazycat requested changes

2022-12-01 00:29 UTC, manateelazycat commented on langserver/omnisharp-mono_windows.json
> +}
If mono can't work, we should remove omnisharp-mono-*.json.

2022-12-01 00:29 UTC, manateelazycat commented on langserver/omnisharp-dotnet.json
> +    "command": ["$HOME/.emacs.d/.cache/omnisharp/OmniSharp.exe",
Use `%USER_EMACS_DIRECTORY%/.cache/omisharp/OmniSharp.exe` instead.

2022-12-01 00:29 UTC, manateelazycat commented on langserver/omnisharp-dotnet_windows.json
> +    "command": [".cache\\omnisharp\\OmniSharp.exe",
Use `%USER_EMACS_DIRECTORY%\\.cache\\omisharp\\OmniSharp.exe` instead.

2022-12-01 00:29 UTC, manateelazycat commented on lsp_bridge.py
> +
We replace `%USER_EMACS_DIRECTORY%` with get-user-emacs-directory here, not write `omnisharp` here, lsp-bridge should not hardcode lsp server name.

2022-12-01 23:56 UTC, manateelazycat requested changes

2022-12-01 23:56 UTC, manateelazycat commented on lsp_bridge.py
> +                user_emacs_dir = get_emacs_func_result("get-user-emacs-directory").replace("/", "\\")
Why need replace / with \\ ? 

\\ is window path splitter, It won't works with Linux.

2022-12-01 23:58 UTC, manateelazycat commented
@JordanAnthonyKing If omnisharp can works with out of box and don't need mono, we need remove omnisharp-mono-*.json files from patch.

2022-12-02 00:35 UTC, JordanAnthonyKing commented
> @JordanAnthonyKing If omnisharp can works with out of box and don't need mono, we need remove omnisharp-mono-*.json files from patch.

Mono is used for older, .net framework projects, as well as the unity game engine. It will be useful to some.

2022-12-03 09:54 UTC, merged