Feat
manateelazycat/lsp-bridge pull request #511
Opened 2023-01-22 13:57 UTC by mumu-lhl

[ruff-lsp](https://github.com/charliermarsh/ruff-lsp) is a LSP implementation for [Ruff](https://github.com/charliermarsh/ruff), an extremely fast Python linter.

2023-01-22 14:52 UTC, manateelazycat commented
相当于代码诊断和修复全部用ruff？

2023-01-22 15:26 UTC, mumu-lhl commented
应该是这样的

2023-01-23 00:54 UTC, manateelazycat requested changes

2023-01-23 00:54 UTC, manateelazycat commented on README.md
> +| [ruff](https://github.com/charliermarsh/ruff-lsp)                                                  | Python                                  | `pip install ruff-lsp`,`lsp-bridge-python-lsp-server`
这一行移动到上面 Python LSP Server 的位置， 相同语言的放在一块。

2023-01-23 00:54 UTC, manateelazycat commented on README.zh-CN.md
> +| [ruff](https://github.com/charliermarsh/ruff-lsp)                                                  | Python                                  | `pip install ruff-lsp`，`lsp-bridge-python-lsp-server`
这一行移动到上面 Python LSP Server 的位置， 相同语言的放在一块。

2023-01-23 00:58 UTC, manateelazycat commented
备注：

https://github.com/manateelazycat/lsp-bridge/blob/6bad830b3df742ce894f4d699cd2d5951f6ffc36/lsp_bridge.py#L169 现在的逻辑是检查 get-multi-lang-server 后就不再检查 get-single-lang-server， 当前 PR 中， 如果 ruff 没有安装， lsp-bridge 会直接退出。

应该修改逻辑是：
1. 先获取 get-multi-lang-server 和 get-single-lang-server 的值
2. 检查 server command 是否存在， 如果不存在尽量从多服务器 fallback 到单服务器， 保持可用性
3. 如果多服务器和单服务器对应的 command 都不存在， 就禁用 lsp-bridge

2023-01-23 01:29 UTC, manateelazycat commented
> 备注：
> 
> https://github.com/manateelazycat/lsp-bridge/blob/6bad830b3df742ce894f4d699cd2d5951f6ffc36/lsp_bridge.py#L169
> 
> 现在的逻辑是检查 get-multi-lang-server 后就不再检查 get-single-lang-server， 当前 PR 中， 如果 ruff 没有安装， lsp-bridge 会直接退出。
> 应该修改逻辑是：
> 
> 1. 先获取 get-multi-lang-server 和 get-single-lang-server 的值
> 2. 检查 server command 是否存在， 如果不存在尽量从多服务器 fallback 到单服务器， 保持可用性
> 3. 如果多服务器和单服务器对应的 command 都不存在， 就禁用 lsp-bridge

等我这段时间把这个逻辑加了再合并这个补丁， 补丁本身的质量很高， 但是我要解决合并后， python诊断马上不可用的问题。

2023-01-23 13:10 UTC, merged

2023-01-23 13:25 UTC, manateelazycat commented
现在lsp-bridge如果遇到 multi-server json 里面定义的 server 命令并没有安装（比如本例的 ruff和ruff-lsp), 会自动fallback到 single-server 模式。