fix #78
manateelazycat/lsp-bridge pull request #88
Opened 2022-05-15 18:27 UTC by vritser

2022-05-15 22:57 UTC, manateelazycat commented
解决一下冲突的问题吧，我晚点看补丁内容。

感谢

2022-05-16 00:22 UTC, manateelazycat commented
建议重写一下，冲突太大了 😂

2022-05-16 02:53 UTC, vritser commented
fixed @manateelazycat

2022-05-16 03:01 UTC, zerolfx commented
CI 里有 error，甚至停不下来了，我手动取消了，你看一下 log。`JDTClassContents` 里面的 `lsp_buffer_uri` 得在 `__init__` 里初始化。

2022-05-16 03:05 UTC, vritser commented
fixed @zerolfx

2022-05-16 03:21 UTC, zerolfx commented on core/handler/__init__.py
> -from core.handler.signature_help import SignatureHelp
这行为什么删？
这里需要 import `JDTClassContents`吗？

2022-05-16 03:21 UTC, zerolfx commented on core/handler/jdt_class_contents.py
> +    start_pos = None
不要用 class variable，你定义一个 `__init__` 函数，调用 `super().__init__`，然后再初始化这两个变量

2022-05-16 03:21 UTC, zerolfx commented on core/handler/jdt_class_contents.py
> +    def send_request(self, file_uri, start_pos):
这里不用父类的定义是因为参数里不能多传 `textDocument` 参数吗？

2022-05-16 03:21 UTC, zerolfx commented on core/lspserver.py
> +        workspace_dir = get_emacs_var("lsp-bridge-java-workspace-dir")
看上去这个 workspace 是 general 的，为什么变量名里有 Java 呢？是仅 Java 可用还是所有语言都可用呢？

2022-05-16 03:21 UTC, zerolfx commented on core/lspserver.py
> +            self.file_uri_dict[filepath] = path_to_uri(uri) if uri.startswith("/") else uri
这看上去很奇怪，`path_to_uri` 的参数应该是叫 `path` 而不是 `uri`？

2022-05-16 03:21 UTC, zerolfx commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
把文件放在 `.emacs.d` 里会不会不妥？最后会被清理掉吗？会不会放在临时目录下更好？

2022-05-16 03:21 UTC, zerolfx commented on core/handler/jdt_class_contents.py
> +        params = self.process_request()
不调用 `process_request` 就不用多定义这个函数了

2022-05-16 03:25 UTC, vritser commented on core/handler/__init__.py
> -from core.handler.signature_help import SignatureHelp
误删了。。

2022-05-16 04:21 UTC, vritser commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
这个是参考的 lsp-java 的目录，不会清理

2022-05-16 04:21 UTC, vritser commented on core/handler/jdt_class_contents.py
> +    def send_request(self, file_uri, start_pos):
已改

2022-05-16 04:21 UTC, vritser commented on core/handler/jdt_class_contents.py
> +    start_pos = None
已改

2022-05-16 04:21 UTC, vritser commented on core/lspserver.py
> +        workspace_dir = get_emacs_var("lsp-bridge-java-workspace-dir")
已改

2022-05-16 04:22 UTC, vritser commented on core/lspserver.py
> +        workspace_dir = get_emacs_var("lsp-bridge-java-workspace-dir")
目前已测试 java，python，ts 都能用，其他的暂无环境测试

2022-05-16 04:25 UTC, vritser commented on core/lspserver.py
> +            self.file_uri_dict[filepath] = path_to_uri(uri) if uri.startswith("/") else uri
`uri` 默认是 filepath，在 `find-definition` 时可能会是 `uri`

2022-05-16 04:25 UTC, vritser commented on core/handler/jdt_class_contents.py
> +        params = self.process_request()
已改

2022-05-16 04:40 UTC, zerolfx commented on core/handler/jdt_class_contents.py
> +    def send_request(self, uri, start_pos):
这个函数可以不要了，都在 `process_request` 里处理（接收两个参数）

2022-05-16 04:40 UTC, zerolfx commented on core/handler/jdt_class_contents.py
> +        super().__init__(fa)
```python
def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
```
type checking 也一并删了吧

2022-05-16 04:40 UTC, zerolfx commented on langserver/jdtls.json
> +            "file:///Users/pi/company/pangcai/ghac"
这个路径是？
前面还有一些路径，估计是你本地的吧

另外在能用的情况下尽可能短一些吧，我看 eglot 就啥参数都没加

2022-05-16 04:43 UTC, zerolfx commented on core/lspserver.py
> +            self.file_uri_dict[filepath] = path_to_uri(uri) if uri.startswith("/") else uri
感觉还是不大好，变量名里带 uri 但其实可能是 uri 也可能是 path，容易感到困惑
要么写一行注释，要么换个名字叫 `xxx_uri_or_path` 之类的

2022-05-16 04:46 UTC, zerolfx commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
这个我不大懂，@manateelazycat 确认一下吧

2022-05-16 05:01 UTC, vritser commented on core/lspserver.py
> +            self.file_uri_dict[filepath] = path_to_uri(uri) if uri.startswith("/") else uri
已改

2022-05-16 05:02 UTC, vritser commented on langserver/jdtls.json
> +            "file:///Users/pi/company/pangcai/ghac"
只保留了必要的参数

2022-05-16 05:59 UTC, manateelazycat commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
白天上班，比较忙，晚上我统一看一下代码。

我早上瞄了一眼，主要的问题有两个：
1. Java的跳转支持感觉是强制特例判断的，对整体逻辑处理有较大冲击
2. Workspace这一块我还没研究， Workspace 的作用是什么？如果 Workspace是标准协议必须实现的一部分，我们能否把 Workspace 统一实现好？ 这样 Java 特例部分的代码比较好抽象出来

总体来说，功能肯定要支持，但是要保证设计合理。

2022-05-16 06:03 UTC, manateelazycat commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
大佬如果对Workspace研究过，可以分享一下 Workspace 的理解，我下班回家就看这个补丁，感谢！

2022-05-16 06:52 UTC, vritser commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
我觉得 workspace 主要是为了支持 `multi-root` ？让多个 workspace-folder 可以共用同一个 `Language Server`

2022-05-16 07:02 UTC, vritser commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
这个 PR 主要做了：
1. 将自定义的 library workspace 加入 ls 的 workspaceFolders
2. 在 find-definition 时，如果要跳转到 library 目录下的文件里：
    1. 使用当前 workspace 的 ls 打开 definition 文件，使用特定的 uri, 比如 java 的 jdt://contents/xxx
    2. 如果要在 library workspace 继续使用 ls 的功能，后续 uri 都要使用 jdt://contents/xxx

2022-05-16 07:49 UTC, manateelazycat commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
lsp-bridge 现在对 workspace 没有任何支持，不知道是不是所有服务器都支持 workspace.

我对这个补丁的理解是，当前项目内的定义跳转没问题，但是要跳转到外部库就需要把外部库通过 workspace 的方式加进来， LSP Server 好找到外部库？

Workspace 还有别的用处吗？

2022-05-16 07:50 UTC, manateelazycat commented on lsp-bridge.el
> +(defcustom lsp-bridge-java-workspace-dir (expand-file-name (locate-user-emacs-file "workspace/"))
我再犹豫的是，如果 Workspace 那么重要，我们是不是先要把 Workspace 协议先独立实现以后再把 Java 专门的支持做了？

这样我们可以清楚哪些是平台框架的代码，哪些是特殊语言的代码？

2022-05-16 11:55 UTC, manateelazycat requested changes

2022-05-16 11:55 UTC, manateelazycat commented on core/lspserver.py
> +
这段直接用 os.path.expanduser , 不要包装了

2022-05-16 15:47 UTC, manateelazycat commented
先按照 https://github.com/manateelazycat/lsp-bridge/issues/92 的逻辑重写吧，感谢补丁。

2022-05-16 15:47 UTC, closed without merging