Kill remote process
manateelazycat/lsp-bridge pull request #953
Opened 2024-05-23 12:22 UTC by werhner

1. add option lsp-bridge-remote-enable-kill-process, which can kill remote lsp-bridge process when Emacs exit
2. add option acm-backend-ctags-max-candidates
3. add command lsp-bridge-ctags-find-def-at-point, which uses xref as front-end.

2024-05-23 14:53 UTC, manateelazycat commented on acm/acm-backend-codeium.el
> +      (delete-region start-position middle-position)
Above code fix some bug?

2024-05-23 15:07 UTC, manateelazycat requested changes

2024-05-23 15:07 UTC, manateelazycat commented on lsp_bridge.py
> +
Why not add close_client code to function "cleanup" ?

2024-05-23 15:07 UTC, manateelazycat commented on lsp-bridge.el
> +      (lsp-bridge-call-sync "close_client"))
Shoud remove those code if code of close_client move to "cleanup" function.

And don't use lsp-bridge-call-sync, it will block Emacs.

2024-05-23 15:07 UTC, manateelazycat commented on lsp-bridge.el
> +
Don't use this function, it will block Emacs

2024-05-23 15:09 UTC, manateelazycat commented
Thanks for patch, I have review code, need adjust. ;)

2024-05-24 02:42 UTC, werhner commented
Thanks for the review, I'll try to adjust these in my spare time.

2024-06-02 09:30 UTC, manateelazycat commented
@werhner Please let me know if this patch can be merged, thank you

2024-06-02 13:53 UTC, manateelazycat requested changes

2024-06-02 13:53 UTC, manateelazycat commented on acm/acm-backend-ctags.el
> +(require 'xref)
Duplicate code?

2024-06-04 13:01 UTC, manateelazycat commented on lsp_bridge.py
>          """Do some cleanup before exit python process."""
close_client should move to below of function comment

2024-06-06 01:39 UTC, manateelazycat commented
@werhner Please adjust code when you have time. I will merge your patch as soon as possible. Thank you.

2024-06-09 03:35 UTC, merged